config/routes.rb
# == Route Map
#
#    Prefix Verb   URI Pattern               Controller#Action
#      root GET    /                         home#index
#     posts GET    /posts(.:format)          posts#index
#           POST   /posts(.:format)          posts#create
#  new_post GET    /posts/new(.:format)      posts#new
# edit_post GET    /posts/:id/edit(.:format) posts#edit
#      post GET    /posts/:id(.:format)      posts#show
#           PATCH  /posts/:id(.:format)      posts#update
#           PUT    /posts/:id(.:format)      posts#update
#           DELETE /posts/:id(.:format)      posts#destroy
#

Rails.application.routes.draw do

  root 'home#index'
  resources :posts

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id            :integer          not null, primary key
#  title         :string
#  body          :text
#  stripped_body :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Post < ActiveRecord::Base
  validates :body, presence: true
  validates :title, presence: true

  before_save :strip_body

  scope :latest, -> { order('created_at desc') }

  paginates_per 12

  def to_param
    [id, title.parameterize].join("-")
  end

  private

  def strip_body
    self.stripped_body = self.body.to_s.strip_tags
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.latest.limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  respond_to :html

  def show
    @post = Post.find(params[:id])
  end

  def index
    @search = Post.ransack(params[:q])
    @posts = @search.result.page(params[:page])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    respond_with @post, location: -> { posts_path }
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(post_params)
    respond_with @post
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_with @post
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def active_class(link_path)
  current_page?(link_path) ? "active" : ""
 end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<%= content_for :jumbotron do %>
  <h1><%= t('.title')%></h1>
  <p class="lead"><%= t('.jumbotron_content') %></p>
  <p>
    <%= link_to new_post_path, class: "btn btn-lg btn-success" do %>
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
      <%= t('posts.new.title') %>
    <% end %>
  </p>
<% end %>

<h3><%=t('.latest_posts')%></h3>
<%= render partial: "posts/grouped_posts", locals: {posts: @posts} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('title') %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Begin page content -->
  <div class="container">
    <%= render "shared/page_header" %>
    <div class="container">
      <%= render "shared/flash" %>
      <%= yield %>
    </div>
  </div>

  <%= render "shared/footer" %>
</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post, html: { class: 'form-horizontal' } do |f| %>

  <%= f.input :title %>
  <%= f.input :body, as: :text, input_html: {cols: 10, rows: 10} %>

  <%= f.button :submit %>
<% end %>

<%= link_to t('back'), :back, class: "btn btn-link" %>

<%= javascript_include_tag Ckeditor.cdn_url %>

<%= javascript_tag do %>
(function() { if (typeof CKEDITOR != 'undefined') { if (CKEDITOR.instances['post_body'] == undefined) { CKEDITOR.replace('post_body', {"customConfig": "<%=asset_path('ckeditor/custom_config.js')%>", "toolbar":"mini"}); } } else { setTimeout(arguments.callee, 50); } })();
<% end %>

app/views/posts/_grouped_posts.html.erb
<% unless posts.empty? %>
  <div class="row marketing">
    <% posts.each_slice(2) do |group|%>
      <div class="col-lg-6">
        <%= render group %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<h4 class="term-highlight"><%= post.title.titleize %></h4>
<p class="term-highlight"><%= truncate(post.stripped_body, {length: 140}) %></p>
<%= link_to t('.see_more'), post_path(post), class: "btn btn-link" %>

app/views/posts/edit.html.erb
<%= render "form" %>

app/views/posts/index.html.erb
<div class="col-lg-12 text-center">
  <%= search_form_for(@search, :builder => SimpleForm::FormBuilder, html: { class: 'form-horizontal' },
    wrapper: :horizontal_input_group) do |f|%>

    <%= f.input :title_or_stripped_body_cont, wrapper: :horizontal_input_group, label: false do%>
      <%= f.input_field :title_or_stripped_body_cont, class: "form-control" %>
      <span class="input-group-btn">
        <%= f.submit t('search'), class: "btn btn-default"%>
      </span>
    <% end %>

  <% end %>
</div>

<div class="col-lg-12">
  <p class="lead"><%= page_entries_info @posts %></p>
</div>

<div class="col-lg-12 text-center">
  <%= paginate @posts, :theme => 'twitter-bootstrap-3' %>
</div>

<div id="search-text">
  <%= render partial: "grouped_posts", locals: {posts: @posts} %>
</div>

<div class="col-lg-12 text-center">
  <%= paginate @posts, :theme => 'twitter-bootstrap-3' %>
</div>

<script type="text/javascript">
  window.App.highlightSearch();
</script>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/show.html.erb
<article>
  <h1><%= @post.title.titleize %></h1>
  <p><%= sanitize @post.body %></p>
</article>

<%= link_to t('edit'), edit_post_path(@post), class: "btn btn-default" %>
<%= link_to t('.delete'), @post, class: "btn btn-danger", method: :delete, data: {confirm: t('.confirm_deletion')} %>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-success fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">Text Search for Machinio Test</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav>
  <ul class="nav nav-pills pull-right">
    <li role="presentation" class="<%= active_class(root_path) %>"><%= link_to t('home_page'), root_path %></li>
    <li role="presentation" class="<%= active_class(posts_path) %>"><%= link_to t('all_posts'), posts_path %></li>
  </ul>
</nav>

app/views/shared/_page_header.html.erb
<div class="header clearfix">
  <%= render "shared/navbar" %>
  <h3 class="text-muted"><%= t('title') %></h3>
</div>

<% if content_for? :jumbotron %>
  <div class="jumbotron">
    <%= yield :jumbotron %>
  </div>
<% end %>